In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
true_df = pd.read_csv("../datasets/True.csv")
true_df

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [3]:
print("Values = NaN")
print(true_df.isna().any())
print("\n\n")

print("Values = 'missing'")
print((true_df == 'missing').any())
print("\n\n")

print("Values = 'empty'")
print((true_df == 'empty').any())
print("\n\n")

Values = NaN
title      False
text       False
subject    False
date       False
dtype: bool



Values = 'missing'
title      False
text       False
subject    False
date       False
dtype: bool



Values = 'empty'
title      False
text       False
subject    False
date       False
dtype: bool

In [4]:
fake_df = pd.read_csv("../datasets/Fake.csv")
fake_df

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [5]:
print("Values = NaN")
print(fake_df.isna().any())
print("\n\n")

print("Values = 'missing'")
print((fake_df == 'missing').any())
print("\n\n")

print("Values = 'empty'")
print((fake_df == 'empty').any())
print("\n\n")

Values = NaN
title      False
text       False
subject    False
date       False
dtype: bool



Values = 'missing'
title      False
text       False
subject    False
date       False
dtype: bool



Values = 'empty'
title      False
text       False
subject    False
date       False
dtype: bool

In [6]:
liar_df = pd.read_csv("../datasets/Liar.csv")
liar_df

,[ID].json,label,statement,subject(s),speaker,speaker's job title,state info,party affiliation,barely true counts,false counts,half true counts,mostly true counts,pants on fire counts,venue
0,11972.json,TRUE,Building a wall on the U.S.-Mexico border will...,immigration,rick-perry,Governor,Texas,republican,30,30,42,23,18,Radio interview
1,11685.json,FALSE,Wisconsin is on pace to double the number of l...,jobs,katrina-shankland,State representative,Wisconsin,democrat,2,1,0,0,0,a news conference
2,11096.json,FALSE,Says John McCain has done nothing to help the ...,"military,veterans,voting-record",donald-trump,President-Elect,New York,republican,63,114,51,37,61,comments on ABC's This Week.
3,5209.json,half-true,Suzanne Bonamici supports a plan that will cut...,"medicare,message-machine-2012,campaign-adverti...",rob-cornilles,consultant,Oregon,republican,1,1,3,1,1,a radio show
4,9524.json,pants-fire,When asked by a reporter whether hes at the ce...,"campaign-finance,legal-issues,campaign-adverti...",state-democratic-party-wisconsin,NaN,Wisconsin,democrat,5,7,2,2,7,a web video
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12782,3419.json,half-true,"For the first time in more than a decade, impo...","energy,oil-spill,trade",barack-obama,President,Illinois,democrat,70,71,160,163,9,a press conference
12783,12548.json,mostly-true,Says Donald Trump has bankrupted his companies...,candidates-biography,hillary-clinton,Presidential candidate,New York,democrat,40,29,69,76,7,a speech on the economy
12784,401.json,TRUE,"John McCain and George Bush have ""absolutely n...",health-care,campaign-defend-america,NaN,"Washington, D.C.",none,0,1,0,2,0,a television ad
12785,1055.json,FALSE,A new poll shows 62 percent support the presid...,health-care,americans-united-change,NaN,NaN,none,1,4,4,1,0,an Internet ad.
12786,9117.json,barely-true,No one claims the report vindicating New Jerse...,"candidates-biography,infrastructure",rudy-giuliani,Attorney,New York,republican,9,11,10,7,3,"comments on NBC's ""Meet the Press"""

In [7]:
print("Values = NaN")
print(liar_df.isna().any())
print("\n\n")

print("Values = 'missing'")
print((liar_df == 'missing').any())
print("\n\n")

print("Values = 'empty'")
print((liar_df == 'empty').any())
print("\n\n")

Values = NaN
[ID].json               False
label                   False
statement               False
subject(s)              False
speaker                 False
speaker's job title      True
state info               True
party affiliation       False
barely true counts      False
false counts            False
half true counts        False
mostly true counts      False
pants on fire counts    False
venue                    True
dtype: bool



Values = 'missing'
[ID].json               False
label                   False
statement               False
subject(s)              False
speaker                 False
speaker's job title     False
state info              False
party affiliation       False
barely true counts      False
false counts            False
half true counts        False
mostly true counts      False
pants on fire counts    False
venue                   False
dtype: bool



Values = 'empty'
[ID].json               False
label                   False
statement               False
subject(s)              False
speaker                 False
speaker's job title     False
state info              False
party affiliation       False
barely true counts      False
false counts            False
half true counts        False
mostly true counts      False
pants on fire counts    False
venue                   False
dtype: bool

In [8]:
from urlextract import URLExtract

extractor = URLExtract()

def remove_urls(text):
    urls = extractor.find_urls(text)
    for url in urls:
        text = text.replace(url, '')
    return text.strip()

def clean_text(text, bert=False):
    if not bert:
        text = str(text).lower()
    text = remove_urls(text)
    if not bert:
        text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def clean_true_and_fake_data(true_df, fake_df, bert=False):
    true_df = true_df.copy()
    true_df.dropna(subset=["title", "text"], inplace=True)
    true_df["text_combined"] = true_df["title"] + " " + true_df["text"]
    true_df["label"] = 1
    true_df = true_df[["text_combined", "label"]]

    fake_df = fake_df.copy()
    fake_df.dropna(subset=["title", "text"], inplace=True)
    fake_df["text_combined"] = fake_df["title"] + " " + fake_df["title"]
    fake_df["label"] = 0
    fake_df = fake_df[["text_combined", "label"]]

    combined_df = pd.concat([true_df, fake_df], ignore_index=True)
    combined_df["text_combined"] = combined_df["text_combined"].apply(lambda s: clean_text(s, bert=bert))
    combined_df["text_combined"] = combined_df["text_combined"].replace('', pd.NA)
    combined_df.rename(columns={"text_combined": "text"}, inplace=True)
    combined_df.dropna(inplace=True)

    return combined_df

def clean_liar_dataset(liar_df, binary=True, bert=False):
    liar_df = liar_df.copy()
    liar_df.dropna(subset=["statement", "label"], inplace=True)

    label_map_binary = {
        'true': 1,
        'mostly-true': 1,
        'half-true': 1,
        'barely-true': 0,
        'false': 0,
        'pants-fire': 0
    }

    label_map = {
        'true': 1,
        'mostly-true': 2,
        'half-true': 3,
        'barely-true': 4,
        'pants-fire': 5,
        'false': 0
    }

    if binary:
        liar_df['label'] = liar_df['label'].str.lower().map(label_map_binary)
    else:
        liar_df['label'] = liar_df['label'].str.lower().map(label_map)
    liar_df.dropna(subset=['label'], inplace=True)
    liar_df['label'] = liar_df['label'].astype(int)

    liar_df['text_cleaned'] = liar_df['statement'].apply(lambda s: clean_text(s, bert=bert))
    liar_df['text_cleaned'] = liar_df['text_cleaned'].replace('', pd.NA)
    liar_df = liar_df[['text_cleaned', 'label']]
    liar_df.rename(columns={"text_cleaned": "text"}, inplace=True)
    liar_df.dropna(inplace=True)

    return liar_df

In [9]:
df1 = clean_true_and_fake_data(true_df=true_df, fake_df=fake_df)
df2 = clean_liar_dataset(liar_df=liar_df)
combined_binary_df = pd.concat([df1, df2], ignore_index=True)
combined_binary_df.to_csv("../cleaned_datasets/cleaned_news_binary.csv", index=False)

df3 = clean_true_and_fake_data(true_df=true_df, fake_df=fake_df, bert=True)
df4 = clean_liar_dataset(liar_df=liar_df, bert=True)
combined_binary_df_bert = pd.concat([df3, df4], ignore_index=True)
combined_binary_df_bert.to_csv("../cleaned_datasets/cleaned_news_binary_bert.csv", index=False)

df6 = clean_liar_dataset(liar_df, binary=False)
combined_multinomial_df = pd.concat([df1, df6], ignore_index=True)
combined_multinomial_df.to_csv("../cleaned_datasets/cleaned_news_multinomial.csv", index=False)

df7 = clean_liar_dataset(liar_df=liar_df, binary=False, bert=True)
combined_multinomial_df_bert = pd.concat([df3, df7], ignore_index=True)
combined_multinomial_df_bert.to_csv("../cleaned_datasets/cleaned_news_multinomial_bert.csv", index=False)